### ISSUE TITLE
Minor: EV contrasts names appear to be missing a "."

### ISSUE THREAD

**Issue by wasciutto** [UNCDEPENdLab/fmri.pipeline#4]
Looks like `EV_block.trial_typeBigBoost` should be `EV_block.trial_type.BigBoost` here:

![image](https://user-images.githubusercontent.com/34407871/233685852-c17326bd-61e3-4d03-9b9c-a31ba0ec4b1e.png)

**Comment by wasciutto** [comment]
My config if needed:
```
# define columns that can be selected in different parts of the model specification
onsets:
  - block_onset

durations:
  - block_duration

wi_factors:
  - trial_type

# events must consist of name, onset, and duration
events:
  block:
    onset: block_onset
    duration: block_duration

# if not otherwise specified, signals will default to unit height regressors with no HRF normalization
signals:
  block:
    event: block
    normalization: none
    value_fixed: 1
    wi_factors: trial_type
    wi_formula: ~ trial_type - 1

l1_models:
  basic_block:
    signals:
      - block
    contrasts:
      include_diagonal: no
```
